### ISSUE TITLE
Missing modules in the output?

### ISSUE THREAD

**Issue by katgit** [bu-rcs/queryModCount#1]
I tried to get a list of all modules used between 2023-01-01 and 2024-03-01 and the list of the modules was very short.
It only included
gcc, python3, make, git, fftw, R, cod, openmpi, miniconda and matlab modules. 
I do not think it is accurate. 
The command I used:
`query_modcount -a 2023-01-01 -b 2024-03-01 -s module`

**Comment by yshen16** [comment]
Sorry this might not be a good design, I had decided to only show the top 10 rows of the output by default, and use '-n' option to request the user-specific rows to return. Also include '-n -1' to indicate to return the full list. 

I can change this behavior if you think by default return the full list is better.

**Comment by katgit** [comment]
Yes, I think it will be more convenient if the output contains all the modules (default behavior) and if someone wants to see only a part of the output you can implement some option for that though my feeling is that it is not needed as one can always use linux commands like `top` and `less` to control the size of the output.

**Comment by yshen16** [comment]
Sounds good. I will make the change.

**Comment by yshen16** [comment]
this issue has been fixed now. Now the default is to show all modules. and use '-n xxx' or '--line_limit xxx' to limit the modules to show.

**Comment by yshen16** [comment]
examples: 
to show all module data: 
query_modcount -a 2023-10-01 -b 2023-12-31 -s user

to show the top 3 module data of the result:  
query_modcount -a 2023-10-01 -b 2023-12-31 -s user -n 3
