### ISSUE TITLE
query-modcount without any command line arguments fails

### ISSUE THREAD

**Issue by katgit** [bu-rcs/queryModCount#2]
Hi Yun, 
When I use `query-modcount` without any command line arguments, I get an error:
```
[ktrn@scc2 ~]$ query_modcount
sh: /scratch/mc_all.csv: Permission denied
rm: cannot remove '/scratch/mc_all.csv': Operation not permitted
=============================================================
SCC Usage sort by module count from 2024-03-17 to 2024-04-17:
=============================================================

metis (1)
metis/5.2.1 (1)
--------------------
```
Instead it should print the same message as when I execute `query-mod count -h`

**Comment by katgit** [comment]
It looks like it fails regardless of what option I use, i.e.

```
[ktrn@scc2 ~]$ query_modcount -a 2024-04-01
sh: /scratch/mc_all.csv: Permission denied
rm: cannot remove '/scratch/mc_all.csv': Operation not permitted
=============================================================
SCC Usage sort by module count from 2024-04-01 to 2024-05-01:
=============================================================
```

**Comment by yshen16** [comment]
opps, I forgot to include this scenario. I will fix the code.

**Comment by yshen16** [comment]
opps, I forgot to consider this scenario. I will modify the code and fix this. 

> Hi Yun, When I use `query-modcount` without any command line arguments, I get an error:
> 
> ```
> [ktrn@scc2 ~]$ query_modcount
> sh: /scratch/mc_all.csv: Permission denied
> rm: cannot remove '/scratch/mc_all.csv': Operation not permitted
> =============================================================
> SCC Usage sort by module count from 2024-03-17 to 2024-04-17:
> =============================================================
> 
> metis (1)
> metis/5.2.1 (1)
> --------------------
> ```
> 
> Instead it should print the same message as when I execute `query-mod count -h`

**Comment by yshen16** [comment]
> It looks like it fails regardless of what option I use, i.e.
> 
> ```
> [ktrn@scc2 ~]$ query_modcount -a 2024-04-01
> sh: /scratch/mc_all.csv: Permission denied
> rm: cannot remove '/scratch/mc_all.csv': Operation not permitted
> =============================================================
> SCC Usage sort by module count from 2024-04-01 to 2024-05-01:
> =============================================================
> ```

Thank you Katia. I will check the code and see why it behaves so and fix it.

**Comment by yshen16** [comment]
fixed. Now when the command is called without any parameter, it will show a short command usage message:

```
[yshen16@scc-bb5 queryModCount]$ query_modcount

     Usage:

         query_modcount 
            [ --before_date|-b before_date ]
            [ --after_date|-a after_date ]
            [ --sortby|-s module|proj|user ]
            [ --line_limit|-n total_lines_to_show ]
            [ --verbose|-v ] 
            [ --version|-V ]
            [ --module|-m modname]
            [ --user|-u login]
            [ --proj|-p projname]
            [ --help|-h]

[yshen16@scc-bb5 queryModCount]$ 
```

**Comment by yshen16** [comment]
the new query_modcount/2.0.0 has been installed, and the issue was fixed in this new version.
