### ISSUE TITLE
Permission denied error

### ISSUE THREAD

**Issue by katgit** [bu-rcs/queryModCount#3]
Hi Yun, 
I tried to use query_modcount today and encountered error. Below is the command line I used and the output I got.
The first line in the output is the error message. In addition, why only python modules are listed?

```
[ktrn@scc1 ~]$ query_modcount -a 2023-01-01
sh: /scratch/mc_all.csv: Permission denied
================================================
SCC Usage sort by  from 2023-01-01 to 2024-07-14
================================================

python3 (47070469)
python3/3.7.3 (45557228)
python3/3.10.12 (652813)
python3/3.6.5 (293903)
python3/3.8.10 (255057)
python3/3.9.4 (117172)
python3/3.8.16 (43599)
python3/3.9.9 (38414)
python3/3.10.5 (29981)
python3/3.7.7 (22051)
python3/3.7.5 (13183)
python3/3.8.10.clean (13078)
python3/3.7.9 (10673)
python3/3.8.6 (10312)
python3/3.7.10 (6648)
python3/3.8.3 (3688)
python3/3.6.9 (1241)
python3/3.6.10 (896)
python3/3.6.12 (532)
--------------------
python3-intel (579)
python3-intel/2021.1.1 (420)
python3-intel/2022.2.0 (159)
```

**Comment by katgit** [comment]
If I use "-m" option, I get the following error:

```
[ktrn@scc1 ~]$ query_modcount -m R
sh: /scratch/mc_all.csv: Permission denied
mv: replace '/scratch/mc_all.csv', overriding mode 0644 (rw-r--r--)?
```

**Comment by katgit** [comment]
It looks like this happens on scc1 only

**Comment by yshen16** [comment]
I know the reason, there is a preexisting /scratch/mc_all.csv on scc1 owned by Brian:
`-rw-r--r-- 1 bgregor scv 2099134 Jul  2 10:53 /scratch/mc_all.csv `

I fixed the code to write to the temporary directory instead of hard coded /scratch/ and also make sure to remove the files after use. This should be fixed.

**Comment by yshen16** [comment]
I closed it since I believe it is fixed.
